CREATE DATABASE toro;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users(
  id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL, 
  cpf CHAR(11) NOT NULL,
  salary DECIMAL NOT NULL,
  gender CHAR(1) NOT NULL,
  politically_exposed BOOLEAN NOT NULL,
  balance NUMERIC(2) NOT NULL DEFAULT 0.00
);